---
- name: Add java repo 
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure Java is installed.
  apt: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"
